name: GoodWords
main: icu.xiangpi.goodwords.main
version: 1.0
api-version: 1.19
commands:
  goodwords:
    aliases:
      - "gw"
    usage: "/goodwords <type>"
    description: "Get a good word"
  gwbroadcast:
    aliases:
      - "gwb"
    usage: "/gwbroadcast <type>"
    description: "broadcast a good word"
  gwreload:
    aliases:
      - "gwr"
    usage: "/gwr"
    description: "relod the config"